"""empty message

Revision ID: 0de0e04dedbf
Revises: a7210b99c32b
Create Date: 2023-01-13 23:46:39.409622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de0e04dedbf'
down_revision = 'a7210b99c32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contadores_username_key', 'contadores', type_='unique')
    op.drop_column('contadores', 'username')
    op.drop_constraint('usuarios_username_key', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('usuarios_username_key', 'usuarios', ['username'])
    op.add_column('contadores', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('contadores_username_key', 'contadores', ['username'])
    # ### end Alembic commands ###
