"""empty message

Revision ID: 3a96775e82eb
Revises: d729526fdc18
Create Date: 2023-01-27 22:27:52.174201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a96775e82eb'
down_revision = 'd729526fdc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completeName', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asesoria')
    # ### end Alembic commands ###
