"""empty message

Revision ID: c8222e52d648
Revises: 541080d915ee
Create Date: 2023-01-27 22:31:57.519058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8222e52d648'
down_revision = '541080d915ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=80), nullable=False))
        batch_op.drop_column('completeName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completeName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
