"""empty message

Revision ID: d729526fdc18
Revises: 0de0e04dedbf
Create Date: 2023-01-18 22:20:06.019823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd729526fdc18'
down_revision = '0de0e04dedbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completeName', sa.String(length=80), nullable=False),
    sa.Column('cedula', sa.String(length=100), nullable=False),
    sa.Column('bancoInfo', sa.String(length=100), nullable=False),
    sa.Column('vehiculosAmount', sa.String(length=100), nullable=False),
    sa.Column('propiedadesAmount', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bancoInfo'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('propiedadesAmount'),
    sa.UniqueConstraint('vehiculosAmount')
    )
    op.create_table('impuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completeName', sa.String(length=80), nullable=False),
    sa.Column('cedula', sa.String(length=100), nullable=False),
    sa.Column('ingresos', sa.String(length=100), nullable=False),
    sa.Column('costos', sa.String(length=100), nullable=False),
    sa.Column('gastos', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('costos'),
    sa.UniqueConstraint('gastos'),
    sa.UniqueConstraint('ingresos')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completeName', sa.String(length=80), nullable=False),
    sa.Column('cedula', sa.String(length=100), nullable=False),
    sa.Column('promedioMensual', sa.String(length=100), nullable=False),
    sa.Column('ocupacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('ocupacion'),
    sa.UniqueConstraint('promedioMensual')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingresos')
    op.drop_table('impuestos')
    op.drop_table('balance')
    # ### end Alembic commands ###
